### ISSUE TITLE
Version information is incorrect

### ISSUE THREAD

**Issue by RedHatter** [osamuaoki/imediff#2]
`imediff --version` does not show the correct version information. For example you can see below that after installing version 2.2 the binary shows version 2.0.

```
$ apt show imediff
Package: imediff
Version: 2.2-1
...
$ apt install imediff
...
$ imediff --version
imediff (version 2.0)
...
```

**Comment by osamuaoki** [comment]
Hi,

I think that was the case.  Sorry but Bulleseye is underfreeze.

Please install package from unstable.  That works for any platform.  It's 2.4 and it
comes with better re-engineered git-ime.

**Comment by osamuaoki** [comment]
Since the latest code already address version issue, let me close.  (There is no functional problem.  Just cosmetic.)
