### ISSUE TITLE
Selected background color option

### ISSUE THREAD

**Issue by RedHatter** [osamuaoki/imediff#3]
Due to how my console is configured when a patch is selected I get bright green on white making the program unusable in color mode. A configurable selected background color would solve this issue.

**Comment by osamuaoki** [comment]
Hi,
On Wed, 2021-07-14 at 15:47 -0700, Ava Johnson wrote:
> Due to how my console is configured when a patch is selected I get bright green on
> white making the program unusable in color mode. A configurable selected background
> color would solve this issue.

I thought it was configurable ....

⟫🥷⟫ imediff -t
Traceback (most recent call last):
  File "/usr/bin/imediff", line 33, in <module>
    sys.exit(load_entry_point('imediff==2.4', 'console_scripts', 'imediff')())
  File "/usr/lib/python3/dist-packages/imediff/__main__.py", line 248, in main
    create_template(config_file)
NameError: name 'config_file' is not defined


Oops, ... some regression.

**Comment by osamuaoki** [comment]
On Wed, 2021-07-14 at 15:47 -0700, Ava Johnson wrote:
> Due to how my console is configured when a patch is selected I get bright green on
> white making the program unusable in color mode. A configurable selected background
> color would solve this issue.

I just uploaded 2.4-3 to unstable/sid.

-t should work now.

Customize as you wish and tell me what still is needed

**Comment by osamuaoki** [comment]
Now that -t works in the latest sid package, you can select your choice of color.  Also, you may be able to customize terminal from terminfo
