### ISSUE TITLE
Split colors for diff mode

### ISSUE THREAD

**Issue by RedHatter** [osamuaoki/imediff#4]
Currently when viewing a section in diff mode the entire section is one color. Spiting the section into multiple colors would increase readability. For example currently the program uses the following.
```
<green>
<<<<<<< a.file
  String get food;
=======
  ForeignKey<Food>? get food;
>>>>>>> b.file
</green>
```
This would be more readable.
```
<gray><<<<<<< a.file</gray>
<blue>  String get food;</blue>
<gray>=======</gray>
<red>  ForeignKey<Food>? get food;</red>
<gray>>>>>>>> b.file</gray>
```

**Comment by osamuaoki** [comment]
You are opening too many issues of similar kinds.  I suspect you are not familiar with this system.
Please continue on other posted thread after trying ~/.imediff customization.
