### ISSUE TITLE
Support additional colors

### ISSUE THREAD

**Issue by RedHatter** [osamuaoki/imediff#5]
Curses supports the full 255 terminal colors (as you can see with the example below) however because of the way imediff consumes colors from the config file only the 8 constants are available for use. There's no reason for this limitation.

```python
import curses

def main(stdscr):
    curses.start_color()
    curses.use_default_colors()
    for i in range(0, curses.COLORS):
        curses.init_pair(i + 1, i, -1)
    try:
        for i in range(0, 255):
            stdscr.addstr(str(i), curses.color_pair(i))
    except curses.ERR:
        # End of screen reached
        pass
    stdscr.getch()

curses.wrapper(main)
```

**Comment by osamuaoki** [comment]
Hi,

On Wed, 2021-07-14 at 16:18 -0700, Ava Johnson wrote:
> Curses supports the full 255 terminal colors (as you can see with the example
> below) however because of the way imediff consumes colors from the config file only
> the 8 constants are available for use. There's no reason for this limitation.
> import curses
> 
> def main(stdscr):
>     curses.start_color()
>     curses.use_default_colors()
>     for i in range(0, curses.COLORS):
>         curses.init_pair(i + 1, i, -1)
>     try:
>         for i in range(0, 255):
>             stdscr.addstr(str(i), curses.color_pair(i))
>     except curses.ERR:
>         # End of screen reached
>         pass
>     stdscr.getch()
> 
> curses.wrapper(main)

This is my first serious Ncurses script ... so bear with me.

I wanted to keep this script as simple as possible.  But I needed some color.  Thus I
am using this mode.

I am open for patch addressing your concern.  It will be nice to detect terminal
type, if possible, to auto-select terminal mode.  At lease we need to support GNOME
terminal on wayland and Linux terminal.

Of course, config code needs to be fixed first.

Regards,

Osamu

**Comment by osamuaoki** [comment]
Hi,

On Wed, 2021-07-14 at 16:18 -0700, Ava Johnson wrote:
> Curses supports the full 255 terminal colors (as you can see with the example
> below) however because of the way imediff consumes colors from the config file only
> the 8 constants are available for use. There's no reason for this limitation.
> import curses
> 
> def main(stdscr):
>     curses.start_color()
>     curses.use_default_colors()
>     for i in range(0, curses.COLORS):
>         curses.init_pair(i + 1, i, -1)
>     try:
>         for i in range(0, 255):
>             stdscr.addstr(str(i), curses.color_pair(i))
>     except curses.ERR:
>         # End of screen reached
>         pass
>     stdscr.getch()
> 
> curses.wrapper(main)


I took a look at color issue.  terminfo(5) goes as:

   Color Handling
       The  curses  library functions init_pair and init_color manipulate the
       color  pairs  and  color  values  discussed  in  this   section   (see
       curs_color(3X) for details on these and related functions).

...


       The setaf/setab and setf/setb capabilities take a single numeric argu‐
       ment each.  Argument values 0-7 of setaf/setab are portably defined as
       follows (the middle column is the symbolic #define  available  in  the
       header for the curses or ncurses libraries).  The terminal hardware is
       free to map these as it likes, but the RGB values indicate normal  lo‐
       cations in color space.

                   Color       #define       Value       RGB
                   black     COLOR_BLACK       0     0, 0, 0
                   red       COLOR_RED         1     max,0,0
                   green     COLOR_GREEN       2     0,max,0
                   yellow    COLOR_YELLOW      3     max,max,0
                   blue      COLOR_BLUE        4     0,0,max
                   magenta   COLOR_MAGENTA     5     max,0,max
                   cyan      COLOR_CYAN        6     0,max,max
                   white     COLOR_WHITE       7     max,max,max

...

So I should keep imediff to limit its color space as now.  If you need fine tuning of
each color, there seems to exists setf or something like that.  (I am not familiar.)

If you find nice color setting scheme via ~/.imediff or via terminfo, let me know. 
It may be worth changing default of offer example of alternative config or readme ...

Regards,

Osamu

**Comment by osamuaoki** [comment]
I thought bullseye version should not have -t bug.  Have you tried -t?

**Comment by osamuaoki** [comment]
Since no response and I see no more issues to address, closing this.
