### ISSUE TITLE
Support diffing directories

### ISSUE THREAD

**Issue by RedHatter** [osamuaoki/imediff#6]
It would be very useful for imediff to support diffing entire directories at a time. So for example
```
imediff -o out_dir dir_a dir_b
```
Would run imediff for each file in dir_a comparing it to a file of the same name in dir_b and outputing the result into out_dir.

**Comment by osamuaoki** [comment]
Hi,

To some extent, I was feeling some lack of capability around what you felt.

On Wed, 2021-07-14 at 16:22 -0700, Ava Johnson wrote:
> It would be very useful for imediff to support diffing entire directories at a
> time. So for example
> imediff -o out_dir dir_a dir_b
> Would run imediff for each file in dir_a comparing it to a file of the same name in
> dir_b and outputing the result into out_dir.

Interesting idea.  

But I thought it requires significant coding .... and I decided to re-engineer git-
ime instead in 2.4.  (See below.)

UI design #1
1. detecting arguments as directory is trivial.
2. scan files and display probably in 2 pane marking files with differences.
3. run imediff on each or select/deselect files

UI design #2
1. detecting arguments as directory is trivial.
2. run imediff on each files (if missing use /dev/null)
3. display them with each file with some separation line

Hmmm... I was originally thinking #1 and this can be best done in a separate code
first.  Too complicated for me to spend time.

Now that I think of this problem, #2 is an idea.  If you create a patch for #2 I
might merge it.  I never thought about it.

If you look at 2.4, the new re-engineered git-ime addresses this problem differently.
invoking git-ime in a directory, it will make a series of single file commits from
HEAD^ and HEAD.  Then we can use the power of "git rebase -i" and easy inspection
tool such as gitk.  We can select which file change to pick and drop with ease.  If
git-ime is run on a single file commit, it starts imediff for you to split commits in
a single file.

What is your thought.

Osamu

**Comment by osamuaoki** [comment]
Since no more response and I see no more issues to address, I am closing this.

Tool should be good at its core strength.  Adding extra-capability which can be easily addressed by using other popular existing tools is undesirable.
